### ISSUE TITLE
.Net Runtime Error

### ISSUE THREAD

**Issue by foldingspace69** [tvn-cosine/tesseract.net#1]
When doing the following:

```
 using (var api = new TessBaseAPI(TesseractConfig.DataPath, TesseractConfig.Language, TesseractConfig.EngineMode))
                {
                    // code below extracted from TessBaseAPI.Process method to allow for 
                    // errors in loading the image file
                    var pix = file.LoadPix();
                    if (pix == null)
                    {
                        throw new Exception($"Unable to load {file.FullName}");
                    }
                    api.SetPageSegMode(PageSegmentationMode.AUTO);
                    api.SetImage(pix);
                    api.Recognize();
                    return api.GetUTF8Text();
                }
```

I get AccessViolationException as shown below:

```
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Tesseract.Native.DllImports.TessBaseAPIRecognize(System.Runtime.InteropServices.HandleRef, IntPtr)
   at Tesseract.TessBaseAPI.Recognize()

```
The OCRing is done via a Windows Service using the latest version of the Tesseract library.

Any ideas?

**Comment by tvn-cosine** [comment]
We have not tested tesseract.net on a windows service yet.  It might be a security feature built into windows thats prohibits raw pointer and memory handling.  Can you maybe run as a local admin and test if you still get the same issue?

**Comment by foldingspace69** [comment]
Hi,

Thanks for responding and the advice.

I have been running the service as a domain admin as the files I need to OCR are on a shared drive. The domain admin is also the admin on the server that I have been trying to run the Windows service on.

**Comment by tvn-cosine** [comment]
Can you maybe start the exact same code in a console app?  Are you getting the same issue?

**Comment by foldingspace69** [comment]
Hi,

Thanks for getting back to me.

I have tried running the exact same code in a console app on Windows 2008 and it appears to work fine. So this probably is some security feature as you have suggested.

Interestingly, if I try and run the same code on Windows 2012 I get a different error:

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'pvt.cppan.demo.google.tesseract.libtesseract400.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Tesseract.Native.DllImports.TessBaseAPICreate()
   at Tesseract.TessBaseAPI..ctor()
   at Tesseract.TessBaseAPI..ctor(String dataPath, String language, OcrEngineMode oem, PageSegmentationMode psm)

Any ideas on the above?

Thanks for your help so far.

**Comment by tvn-cosine** [comment]
Ensure the lib folder and sub folders exist on deployment machine. If they dont, ensure the dlls included in the lib folder is set to copyToOutput. We are looking at settings within the nuspec file that will automatically change this when nuget installed.

**Comment by foldingspace69** [comment]
I had the same folder on the 2008 server as I did on the 2012 server which included the lib and sub folders, so I thought it was strange that it had an issue with missing DLLs

**Comment by tvn-cosine** [comment]
One of the [tvn-cosine](https://github.com/tvn-cosine) team members suggested that you double check if all the [Leptonica](https://github.com/DanBloomberg/leptonica) libraries were copied over as described [here](https://github.com/tvn-cosine/leptonica.net/wiki/How-to-use-leptonica.net).  This project also includes a nuget reference to [leptonica.net](https://www.nuget.org/packages/leptonica.net/).
