### ISSUE TITLE
How do I convert Bitmap to Pix?

### ISSUE THREAD

**Issue by whatohyou** [tvn-cosine/tesseract.net#10]
Long story short, I capture the screen as bitmap then read some pixels and cut & paste some pixels.
Then I want to run it on tvn-cosine ocr.
However since tvn-cosine tesseract will only accept leptonica.pix, I'll have to save the bitmap to a tiff image file in the harddisk drive before using api.setimage(temp.tif); ...
It isn't very efficient.

 MemoryStream byteStream = new MemoryStream();
 Bmp.Save(byteStream, System.Drawing.Imaging.ImageFormat.Tiff);
using (TessBaseAPI api = new TessBaseAPI(dataPath, language, OcrEngineMode.DEFAULT, PageSegmentationMode.AUTO))
            {
                api.SetImage(byteStream);//it will not work. It says you can't convert memory stream to pix.
            }

--
People were having similar problems as follow:
https://github.com/charlesw/tesseract/issues/61
charlesw made pixconverter function that converts bitmap to pix.
When I tried it, it says  tesseract.pix is not leptonica.pix ...

Is there any solutions? How do I convert bitmap to leptonica.pix in the memory?

**Comment by whatohyou** [comment]
http://tpgit.github.io/Leptonica/bmpio_8c_source.html#l00057
It seems there is source code to read bmp memory stream to Leptonica.Pix but I don't know how to use it in c#.

**Comment by tvn-cosine** [comment]
We have not created in memory examples in wiki yet. 
Please use this static class: 

https://github.com/tvn-cosine/leptonica.net/blob/master/leptonica.net/Implementations/BmpIO.cs

**Comment by tr4nquility** [comment]
Hi @tvn-cosine ,
Any news on this enhancement? 
I also need this functionality of TessBaseAPI reading an image, either from object or memory stream.
Perhaps if you can show us how to use BmpIO.pixReadMemBmp() method in the mean time?
Thank you.

**Comment by CSharpReaper** [comment]
Hi,
you can use it in this way for a stream.

var image = Image.FromStream(stream);
var ms = new MemoryStream();
image.Save(ms, ImageFormat.Bmp)
var bytes = ms.ToArray();
Pix pix;
fixed(byte* ptr = bytes) {
pix = BmpIO.pixReadMemBmp((IntPtr)ptr, (IntPtr)bytes.Length)
}

Note: Make sure your project allows unsave code!

**Comment by tvn-cosine** [comment]
@CSharpReaper , Thanks for code.  This was implemented in the latest releases of the leptonica nuget packages.

var pix = Pix1.pixReadFromMemoryStream(System.IO.Stream stream);

[`https://www.nuget.org/packages/leptonica.net/`](https://www.nuget.org/packages/leptonica.net/).
[`https://www.nuget.org/packages/tesseract.net/`](https://www.nuget.org/packages/tesseract.net/).
