### ISSUE TITLE
How to make box?

### ISSUE THREAD

**Issue by maoleigepu** [tvn-cosine/tesseract.net#11]
Hi
I get the text content of a image, but I can't get position information which is stored in box file.
Is there any solution to get the box file?

**Comment by maoleigepu** [comment]
@tvn-cosine 
Hi 
I got the box file. 
var tessBaseAPI = new TessBaseAPI(dataPath,language,oem,psm);
var boxInfo = tessBaseAPI.GetBoxText(1);

And the boxInfo is the content of box file.


However, I have to deal with the encoding error.
The source code of 'GetBoxText()‘ method is that.
public string GetBoxText(int pageNumber)
        {
            IntPtr pointer = Native.DllImports.TessBaseAPIGetBoxText((HandleRef)this, pageNumber);
            if (pointer == null || pointer == IntPtr.Zero)
            {
                return null;
            }
            else
            {
                string returnObject = Marshal.PtrToStringAnsi(pointer);
                Native.DllImports.TessDeleteText(pointer); //Delete the text pointer to clear memory
                return returnObject;
            }
        }

If you change 'Marshal.PtrToStringAnsi(point)' to 'Marshaling.PtrToStringUTF8(point)',
it will solve the encoding problem.

So wil you please change this method to update nuget package.

**Comment by tvn-cosine** [comment]
Thank you for identifying the bug. 

An update has been released. 4.0.0.14

Kind regards,
tvn-cosine
