### ISSUE TITLE
set location of cppan DLL

### ISSUE THREAD

**Issue by yasindn** [tvn-cosine/tesseract.net#12]
Hi
Can you add feature to set location folder of DLL by manual like tesdata folder
tanx

**Comment by tvn-cosine** [comment]
We initially included that ability, but countless errors were experienced when loading the dlls from the specified source.

A decision was made to roll back until the tesseract.net functionality is complete before attempting to do it again.

This will be definitely  rolled out in future versions but not at this stage.

Kind regards,
tvn-cosine

**Comment by tvn-cosine** [comment]
Tesseract.Native.DllImports.TesseractDirectory = @"C:\Test\tesseract"; //<-- Add this line
            //Remember that the x86 / x64 folder structure
            TessBaseAPI tessBaseAPI = new TessBaseAPI();

            System.Console.WriteLine("The current version is {0}", tessBaseAPI.GetVersion());

            System.Console.WriteLine("Press any key to quit...");
            System.Console.ReadKey();
