### ISSUE TITLE
Extracting Text - tessBaseAPI

### ISSUE THREAD

**Issue by michalletniowski** [tvn-cosine/tesseract.net#14]
Hi!

I Would like to ask you about using tesseract in .NET (C#)

In manual "Extracting Text"
![issue](https://user-images.githubusercontent.com/41157073/42990782-fde37e94-8c03-11e8-995f-3a87f1b21ccb.PNG)

There is a line:
![setimage](https://user-images.githubusercontent.com/41157073/42990816-15cf4268-8c04-11e8-9097-db0b043462f8.PNG)

And Now...
This is a way to input image form source, but I want to put the image from stream.
So I tried this constructor:
![constructor](https://user-images.githubusercontent.com/41157073/42991084-d8565b78-8c04-11e8-9184-82521fbd9fb3.PNG)

I'm wondering if it is a good method at all? And if it is, What should I assign to UIntPtr imagedata variable to make it work well, and how to extract it from image in MagickImage/Bitmap/Image/Stream type?

**Comment by tvn-cosine** [comment]
Please refer to [this](https://github.com/tvn-cosine/tesseract.net/issues/10#issuecomment-399080976) post.
