### ISSUE TITLE
problem processing OCR

### ISSUE THREAD

**Issue by plsft** [tvn-cosine/tesseract.net#16]
I'm getting poor output from processing the attached sample file. It's mostly tabular data. I've tried cleaning up the image by making it B&W with the MagickImage library to no avail.  I've played with tessedit_char_whitelist variables but the output isn't even close. 

Any thoughts?

**Comment by jtdw1c** [comment]
You might try Infranview or some other app which will allow you to save as a TIFF format.

**Comment by tvn-cosine** [comment]
We have not tested using tabular data but occording to [this](https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality#page-segmentation-method) post, you need to play around with the [Tesseract.PageSegmentationMode](https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality#page-segmentation-method) settings.

They suggest changing it to:

`PageSegmentationMode.SINGLE_BLOCK;`
