### ISSUE TITLE
Tesseract 4.0.0 not working while adding as reference in .net web service

### ISSUE THREAD

**Issue by 5hivams** [tvn-cosine/tesseract.net#18]
I made a class library using your library from nuget, and same class library is working fine in .net console project but it's not working .net web service project while adding as same reference. 
I tried to add your library using in web api project but getting same exception when we initialize TessbaseAPI class.

tessBaseAPI = new TessBaseAPI(); 

Here is the exception I am getting on above line:

System.TypeInitializationException: 'The type initializer for 'Tesseract.Native.DllImports' threw an exception.'

Here is the stack trace: 
 "   at Tesseract.Native.DllImports.TessBaseAPICreate()\r\n  
 at Tesseract.TessBaseAPI..ctor()"

**Comment by 5hivams** [comment]
Tried another ways too to initialize TessBaseAPI but never succeed:
Here is the snippet of the code:

      string dataPath = "./tessdata/";
            string language = "eng";
            OcrEngineMode oem = OcrEngineMode.DEFAULT;
            PageSegmentationMode psm = PageSegmentationMode.AUTO_OSD;

            TessBaseAPI tessBaseAPI = new TessBaseAPI(dataPath, language, oem, psm);

**Comment by jtdw1c** [comment]
It's probably the same issue as this one:

DLL can't find dependencies when run from a location different from that of the DLL

It is in the issues list.

**Comment by 5hivams** [comment]
Thanks for your reply, How soon we can get any permanent solution for this ?

**Comment by tvn-cosine** [comment]
Download Latest version tesseract / leptonica source

Tesseract.Native.DllImports.TesseractDirectory = @"C:\Test\tesseract"; //<-- Add this line
        //Remember that the x86 / x64 folder structure
        TessBaseAPI tessBaseAPI = new TessBaseAPI();

        System.Console.WriteLine("The current version is {0}", tessBaseAPI.GetVersion());

        System.Console.WriteLine("Press any key to quit...");
        System.Console.ReadKey();

**Comment by tvn-cosine** [comment]
I however believe Microsoft has strict security rules relating to web api dll interopt.  Have not tested on web api yet but have heard security related issues as the executing app pools reside in different directory from where actual web source lies.
