### ISSUE TITLE
support 2 or 3 languages

### ISSUE THREAD

**Issue by yasindn** [tvn-cosine/tesseract.net#2]
Hi
Can this package support 2 languages at same time?

**Comment by tvn-cosine** [comment]
We believe the main Tesseract engine does have that ability, but we have not tested it as such.  According to online examples you must specify the different languages with a + sign between.  Example below

`string dataPath = "./tessdata/";
string language = "eng+jpn";
string inputFile = "./input.png";
OcrEngineMode oem = OcrEngineMode.DEFAULT;
PageSegmentationMode psm = PageSegmentationMode.AUTO_OSD;

TessBaseAPI tessBaseAPI = new TessBaseAPI();

// Initialize tesseract-ocr 
if (!tessBaseAPI.Init(dataPath, language, oem))
{
   throw new Exception("Could not initialize tesseract.");
}

// Set the Page Segmentation mode
tessBaseAPI.SetPageSegMode(psm);

// Set the input image
Pix pix = tessBaseAPI.SetImage(inputFile);

// Recognize image
tessBaseAPI.Recognize();

ResultIterator resultIterator = tessBaseAPI.GetIterator();

// Extract text from result iterator
StringBuilder stringBuilder = new StringBuilder();
PageIteratorLevel pageIteratorLevel = PageIteratorLevel.RIL_PARA;
do
{
   stringBuilder.Append(resultIterator.GetUTF8Text(pageIteratorLevel));
} while (resultIterator.Next(pageIteratorLevel));

tessBaseAPI.Dispose();
pix.Dispose();`
