### ISSUE TITLE
How to OCR a multipage tiff and output to a multipage pdf?

### ISSUE THREAD

**Issue by Gleedo** [tvn-cosine/tesseract.net#3]
Hi, I am struggling to work out how to get tesseract.net to output a multipage pdf from a multipage tiff input file....any thoughts appreciated.

**Comment by tvn-cosine** [comment]
We have not tested a multipage tiff pdf generation yet.  If Tesseract does not support it, then a work around might be to OCR individual pages and use a pdf package such [https://www.nuget.org/packages/iTextSharp/](https://www.nuget.org/packages/iTextSharp/) to merge the separate pages.

The following link might help to generate a searchable pdf
[https://github.com/tvn-cosine/tesseract.net/wiki/Creating-a-searchable-Pdf](https://github.com/tvn-cosine/tesseract.net/wiki/Creating-a-searchable-Pdf)
