### ISSUE TITLE
DLL imports are missing throw exception after calling TessBaseAPI

### ISSUE THREAD

**Issue by esritines** [tvn-cosine/tesseract.net#6]
Just that, throws an error after called var tessBaseAPI = new TessBaseAPI();

            var location = HttpContext.Current.Server.MapPath("~");

            string dataPath = location + "tessdata";
            string language = "esp";

            OcrEngineMode oem = OcrEngineMode.TESSERACT_ONLY;
            PageSegmentationMode psm = PageSegmentationMode.AUTO_OSD;

            var tessBaseAPI = new TessBaseAPI();

            // Initialize tesseract-ocr 
            if (!tessBaseAPI.Init(dataPath, language, oem))
                throw new Exception("Could not initialize tesseract.");

            // Set the Page Segmentation mode
            tessBaseAPI.SetPageSegMode(psm);

            // Set the input image
            var pix = tessBaseAPI.SetImage(inputFile);

            // Recognize image
            tessBaseAPI.Recognize();

            var resultIterator = tessBaseAPI.GetIterator();

            // Extract text from result iterator
            var stringBuilder = new StringBuilder();
            var pageIteratorLevel = PageIteratorLevel.RIL_PARA;

            do
            {
                stringBuilder.Append(resultIterator.GetUTF8Text(pageIteratorLevel));
            } while (resultIterator.Next(pageIteratorLevel));

            tessBaseAPI.Dispose();
            pix.Dispose();

            return CleanResult(stringBuilder.ToString());

**Comment by tvn-cosine** [comment]
Hi,

Please ensure that all the dlls included are copied to the output directory as described in this [post](https://github.com/tvn-cosine/tesseract.net/wiki/How-to-use-tesseract.net).  This project does not only use the tesseract dll but uses the [Leptonica](https://github.com/DanBloomberg/leptonica) as well.

Please post the exception stack trace you are receiving.

**Comment by esritines** [comment]
Stille gettin the error:

An exception of type 'System.TypeInitializationException' occurred in tesseract.net.dll but was not handled in user code

Additional information: Se produjo una excepción en el inicializador de tipo de 'Tesseract.Native.DllImports'.

I already set the configuration CopyToOutputDirectory: Copy Always

**Comment by maoleigepu** [comment]
@esritines 
Hi,
I have to face the same problem, do you have a solution?

**Comment by maoleigepu** [comment]
@esritines 
Hi
Sorry to bother you. I got the solution.
You need to set the copy to new folder property of dll in lib folder .

**Comment by cGiesen** [comment]
Hello,
I like to reopen the question.
I have the 'problem' that the LIB files allways has to locat in the folder, I USE the DLL.

I wrote a wraper, to use tesseract in vbScript. The DLL and all files a stored in Programfiles.
I start the script some ware else an I have to copy the LIB folder to that place as well.

Is there a way, that I can use tham from my program files folder?

Regards
Carsten

**Comment by sera0731** [comment]
I also face same problem. 
I want to develop webservice with tesseract.net.
But I think they don't import dll files from my root project folder but they import dll files from iis root folder.
Should I always copy bin folder from my project to iis root directory?
